version: "3.9" # optional since v1.27.0
services:
  scrapper:
    build:
      context: .
      target: builder
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 6
        window: 120s
